echo off
ren agrivenb.mid agricola_o_venus_bant.mid 
ren quadro-p.mid alison_quadro_pavin.mid 
ren agnusdei.mid anon_agnus_dei.mid 
ren andiwere.mid anon_an_I_were_a_maiden.mid 
ren anglvirg.mid anon_angelus_ad_virginem.mid 
ren anglvirm.mid anon_angelus_ad_virginem2.mid 
ren waswalkg.mid anon_as_I_was_walking.mid 
ren bepeace.mid anon_be_peace_ye_make_me_spill_my_ale.mid 
ren belfiore.mid anon_bel_fiore_danca.mid 
ren benedica.mid anon_benedicamus_domino.mid 
ren cobhrnpp.mid anon_cobblers_hornpipe.mid 
ren conductu.mid anon_conductus.mid 
ren cons12.mid anon_consort_xii.mid 
ren cntryjig.mid anon_country_jig.mid 
ren czaldy.mid anon_czaldy_waldy.mid 
ren dadme.mid anon_dadme_albricias_hijos_d'eva.mid 
ren katzpfot.mid anon_die_katzenpfote.mid 
ren duo17thc.mid anon_duo.mid 
ren eladon.mid anon_e_la_don_don_virges_maria.mid 
ren edibeo.mid anon_edi_beo_thu_hevene_quene.mid 
ren elslein.mid anon_elslein_liebstes_elslein.mid 
ren gaudete.mid anon_gaudete.mid 
ren whatshal.mid anon_hey_ho_what_shall_I_say.mid 
ren ichsegad.mid anon_ic_seg_adieu.mid 
ren jeanisab.mid anon_jeanette_isabella.mid 
ren bergamas.mid anon_la_bergamasca.mid 
ren giromett.mid anon_la_girometta.mid 
ren la_rotta.mid anon_la_rotta.mid 
ren lamntris.mid anon_lamento_di_tristana.mid 
ren montagnu.mid anon_montagnura.mid 
ren nota39.mid anon_nota_39.mid 
ren nota40.mid anon_nota_40.mid 
ren nota41.mid anon_nota_41.mid 
ren godpan.mid anon_now_thanked_be_the_great_god_pan.mid 
ren omniscur.mid anon_omnis_curet_homo.mid 
ren paseagua.mid anon_pase_el_agua_ma_julieta.mid 
ren patapan.mid anon_patapan.mid 
ren pavnshwm.mid anon_pavane_for_shawm_band.mid 
ren pipfancy.mid anon_piper's_fancy.mid 
ren riuriu.mid anon_riu_riu_chiu.mid 
ren saltare2.mid anon_saltarello_2.mid 
ren saltare3.mid anon_saltarello_3.mid 
ren sifortun.mid anon_si_fortune.mid 
ren singcare.mid anon_sing_care_away.mid 
ren icumen.mid anon_sumer_is_icumen_in_1.mid 
ren icumen2.mid anon_sumer_is_icumen_in_2.mid 
ren tantasou.mid anon_tant_a_soutille.mid 
ren tempflor.mid anon_tempus_adest_floridum.mid 
ren agincour.mid anon_the_agincourt_carol.mid 
ren boarhead.mid anon_the_boar's_head_carol_1.mid 
ren boarhed2.mid anon_the_boar's_head_carol_2.mid 
ren coventry.mid anon_the_coventry_carol.mid 
ren hollyivy.mid anon_the_holly_and_the_ivy.mid 
ren morris.mid anon_the_shepherd's_hey.mid 
ren wassail.mid anon_the_wassail_song.mid 
ren no_rose.mid anon_there_is_no_rose_of_swich_vertu.mid 
ren daydaws.mid anon_this_day_day_daws.mid 
ren veniveni.mid anon_veni_veni_immanuel.mid 
ren verbcaro.mid anon_verbum_caro_factum_est.mid 
ren arbbelqu.mid arbeau_belle_qui_tiens_ma_vie.mid 
ren attdnsui.mid attaignant_dance_suite.mid 
ren basnfan5.mid bassano_fanfare5.mid 
ren basnrc11.mid bassano_ricercar11.mid 
ren bennserv.mid bennett_servant_of_his_mistress.mid 
ren bradanma.mid brade_der_ander_mascharada.mid 
ren braderma.mid brade_der_erste_mascarada_des_pfaltzgraffen.mid 
ren busnfods.mid busnois_fortuna_desperata.mid 
ren byrdgrnw.mid byrd_hey_ho_to_the_greenwood.mid 
ren amorchat.mid caccini_amor_ch'attendi.mid 
ren comopodn.mid cantigas_como_poden.mid 
ren cdsmamar.mid cantigas_santa_maria_amar.mid 
ren caranonc.mid cara_io_non_compro_piu_speranza.mid 
ren clkcwhrv.mid clark_wherever_you_go.mid 
ren clkcwngr.mid clark_wind_on_a_ground.mid 
ren compbarb.mid compere_alons_fere_nos_barbes.mid 
ren cornadiu.mid cornysh_adieu_corage_adieu.mid 
ren cornrobn.mid cornysh_ah_robin_gentle_robin.mid 
ren cornblow.mid cornysh_blow_thy_horne_hunter.mid 
ren corntrly.mid cornysh_trolly_lolly.mid 
ren daggdown.mid daggere_18_downbery_down.mid 
ren daggdowa.mid daggere_18a_downbery_down.mid 
ren jeurobin.mid delahalle_jeu_de_robin_et_marion.mid 
ren torralta.mid delatorre_alta.mid 
ren despvive.mid desprez_vive_le_roy.mid 
ren dowshep.mid dowland_a_shepherd_in_a_shade.mid 
ren dowcmagn.mid dowland_come_again_sweet_love_doth_now_invite.mid 
ren dowcomp.mid dowland_if_my_complaints.mid 
ren encisoyc.mid encina_soy_contento_y_vos_servido.mid 
ren encitris.mid encina_triste_espana_sin_ventura.mid 
ren eraraute.mid erars_au_tems_pascor.mid 
ren escolque.mid escobar_lo_que_queda_es_lo_seguro.mid 
ren escoplen.mid escobar_missa_de_nuestra_señora-pleni_sunt.mid 
ren escovarq.mid escobar_pasame_por_dios_varquero.mid 
ren escoserr.mid escobar_paseisme_aor'_alla_serrana.mid 
ren escovenc.mid escobar_vencedores_son_tus_ojos.mid 
ren eusr3ten.mid eustacio-romano_tenor_cum_tenore3.mid 
ren eusr7ten.mid eustacio-romano_tenor_cum_tenore7.mid 
ren festumag.mid festa_l'ultimo_di_de_maggio.mid 
ren festopas.mid festa_o_passi_sparsi.mid 
ren gabacanz.mid gabrieli_canzone.mid 
ren gervalm1.mid gervaise_almande_1.mid 
ren gervbbg9.mid gervaise_bransle_de_bourgongne_9.mid 
ren gervbrg1.mid gervaise_bransle_gay_1.mid 
ren gervbrg2.mid gervaise_bransle_gay_2.mid 
ren gervbrg3.mid gervaise_bransle_gay_3.mid 
ren gervbrg4.mid gervaise_bransle_gay_4.mid 
ren gervbrg5.mid gervaise_bransle_gay_5.mid 
ren gervbrg6.mid gervaise_bransle_gay_6.mid 
ren gervbrs1.mid gervaise_bransle_simple_1.mid 
ren gervgaig.mid gervaise_gaillard_de_la_guerre.mid 
ren gervgtg1.mid gervaise_gaillard_du_ton_de_la_guerre1.mid 
ren gervgtg2.mid gervaise_gaillard_du_ton_de_la_guerre2.mid 
ren gervgaic.mid gervaise_gaillard_est_il_conclud.mid 
ren gervgaia.mid gervaise_gaillard_l'admiral.mid 
ren gervgais.mid gervaise_gaillard_si_je_m'en_vois.mid 
ren gervpavg.mid gervaise_pavanne_de_la_guerre.mid 
ren gervpavc.mid gervaise_pavanne_est_il_conclud.mid 
ren gervpava.mid gervaise_pavanne_l'admiral.mid 
ren gervpavs.mid gervaise_pavanne_si_je_m'en_vois.mid 
ren jubilo.mid gesius_in_dulci_jubilo.mid 
ren gibbswan.mid gibbons_the_silver_swanne.mid 
ren ghizdetu.mid haynevanghizeghem_de_tous_bien_plane.mid 
ren hen4sanc.mid henryvi_sanctus.mid 
ren hen8cn24.mid henryviii_consort24.mid 
ren hen8con4.mid henryviii_consort4.mid 
ren hen8envr.mid henryviii_en_vray_amoure.mid 
ren hen8gnpr.mid henryviii_gentil_prince.mid 
ren hen8hmdm.mid henryviii_helas_madame.mid 
ren hen8pas2.mid henryviii_passetyme_with_good_cumpanye7.mid 
ren hen8past.mid henryviii_pastime_with_good_company7a.mid 
ren hen8tndr.mid henryviii_tander_nauken.mid 
ren hen8whto.mid henryviii_whereto_shoulde_i_expresse.mid 
ren hiltcmfl.mid hilton_come_follow_follow_me.mid 
ren hiltcmmf.mid hilton_come_merry_men_follow.mid 
ren hiltsmfr.mid hilton_now_when_the_summer's_fruits.mid 
ren hiltkldr.mid hilton_what_shall_he_have_that_kill'd_the_deer.mid 
ren holbfrui.mid holborne_fruit_of_love.mid 
ren holbmvyl.mid holborne_mvylinda.mid 
ren holbchoi.mid holborne_the_choice.mid 
ren holbwidm.mid holborne_the_widow's_mite.mid 
ren isagleid.mid isaac_gross_leid_muss_ich_tragen.mid 
ren isainnsr.mid isaac_innsbruck_ich_muss_dich_lassen_r.mid 
ren isainnsv.mid isaac_innsbruck_ich_muss_dich_lassen_v.mid 
ren isa-lamy.mid isaac_la_my.mid 
ren lndnbllt.mid landini_ballata.mid 
ren lndnchip.mid landini_chi_piu_vuol_sapere.mid 
ren lndnpart.mid landini_partesi_con_dolore.mid 
ren lndnques.mid landini_questa_fanciull'_amor.mid 
ren lassoich.mid lassus_oi_ch'el_mio_largo_pianto.mid 
ren las-mai.mid lassus_wohl_kommt_der_mai.mid 
ren luthvhim.mid luther_vom_himmel_hoch.mid 
ren machbont.mid machaut_de_bonte_de_valour.mid 
ren machdous.mid machaut_dous_amis.mid 
ren mnchqupu.mid manchicourt_que_puis_je_lors.mid 
ren morlcan5.mid morley_blow_shepherds_blow_your_pipes.mid 
ren morlcan6.mid morley_farewell_disdainful.mid 
ren morlcan4.mid morley_good_morrow_fair_ladies_of_the_may.mid 
ren morlcan2.mid morley_lady_those_eyes.mid 
ren morlnews.mid morley_o_sing_unto_the_lord_a_new_song.mid 
ren morlcan9.mid morley_say_dear_will_you_not_have_me.mid 
ren morlcan7.mid morley_say_what_ails_my_darling.mid 
ren morlcan8.mid morley_see_mine_own_sweet_jewel.mid 
ren morlcan1.mid morley_springtime_mantleth_every_bough.mid 
ren morlcan3.mid morley_where_art_thou_wanton.mid 
ren moulamys.mid moulu_amy_souffrez.mid 
ren obrtandr.mid obreht_tandernaken.mid 
ren patadlla.mid patavino_dilla_da_l'acqua.mid 
ren peroalle.mid perotin_alleluya.mid 
ren peroalna.mid perotin_alleluya_nativitas.mid 
ren 980429.mid perotin_alleluya_nativitas_concert.mid 
ren pesedlct.mid pesenti_dal_lecto_me_levava.mid 
ren rufty.mid playford_rufty_tufty.mid 
ren prabal10.mid praetorius_ballet_268.mid 
ren prabou8.mid praetorius_bouree_32a.mid 
ren prabou9.mid praetorius_bouree_32b.mid 
ren pracour2.mid praetorius_courante_117.mid 
ren pracour1.mid praetorius_courante_183.mid
ren einros.mid praetorius_es_ist_ein_reis_entsprungen.mid 
ren pragaval.mid praetorius_gavotte_1.mid 
ren pragavx.mid praetorius_gavotte_1_abcf.mid 
ren pragil7.mid praetorius_gavotte_1_gillotte.mid 
ren pragav1.mid praetorius_gavotte_1a.mid 
ren pragav2.mid praetorius_gavotte_1b.mid 
ren pragav3.mid praetorius_gavotte_1c.mid 
ren pragav4.mid praetorius_gavotte_1d.mid 
ren pragav5.mid praetorius_gavotte_1e.mid 
ren pragav6.mid praetorius_gavotte_1f.mid 
ren praspag7.mid praetorius_spagnoletta_27.mid 
ren pravol11.mid praetorius_volte_202.mid 
ren scrmshwm.mid praetorius_volte_202_shawms.mid 
ren pravol12.mid praetorius_volte_210.mid 
ren rampbacc.mid rampolini_bacco_bacco.mid 
ren 3ravens.mid ravenscroft_3ravens.mid 
ren januns.mid richardi_ja_nuns_hons_pris.mid 
ren senelse.mid senfl_ach_elslein_liebes_elselein_mein.mid 
ren senalsab.mid senfl_als_ab_und_hin.mid 
ren sentaget.mid senfl_es_taget_vor_dem_walde.mid 
ren sentgfor.mid senfl_es_taget_vor_dem_walde-fortuna.mid 
ren senbaurt.mid senfl_es_was_eins_bauren_toechterlein.mid 
ren seneswol.mid senfl_es_wollt'_ein_maidlein_wasser_hol'n.mid 
ren senistu3.mid senfl_ich_stuend_an_einem_morgen.mid 
ren senlumag.mid senfl_lust_mag_mein_herz.mid 
ren senmrgf1.mid senfl_wann_ich_des_morgens_frueeh_aufsteh'_primum.mid 
ren senmrgf2.mid senfl_wann_ich_des_morgens_frueeh_aufsteh'_secundum.mid 
ren senwmai1.mid senfl_wohl_kumbt_der_mai1.mid 
ren senwmai2.mid senfl_wohl_kumbt_der_mai2.mid 
ren sermalle.mid sermisy_allez_souspirs.mid 
ren sermtviv.mid sermisy_tant_que_vivrai.mid 
ren song-ass.mid song_of_the_ass_1.mid 
ren songassf.mid song_of_the_ass_2.mid 
ren susallem.mid susato_allemande.mid 
ren sushoboe.mid susato_hoboeckentanz.mid 
ren vecsoben.mid vecchi_so_ben_mi_cha_bon_tempo.mid 
ren whimhrkh.mid white_hark_how_the_woods_do_ring.mid 
ren wllaledu.mid willaert_le_dur_travail.mid 
ren hallfima.mid delahalle_fi_maris_de_vostre_amour.mid 
ren inhcanni.mid anon_verbum_caro_factum_est_in_hoc_anni_circulo.mid 
ren jollfost.mid anon_i_am_a_jolly_foster.mid 
ren resolaud.mid anon_resonet_in_laudibus.mid 
ren cdsm1.mid cantigas_de_santa_maria_1.mid 
ren estamp4.mid anon_la_quarte_estampie_royal.mid 
ren jaypryse.mid anon_jay_pryse_amours.mid 
ren roundel.mid anon_roundel_1453.mid 
ren violtest.mid viol_test.mid 
ren vivrefrn.mid anon_viv_el_gran_re_don_fernando.mid 
ren whilshep.mid tye_while_shepherds_watched_their_flocks_by_night.mid 
ren amysouff.mid delete_ths_one.mid 
ren dansroy1.mid anon_danse_(ductia_13)_2.mid 
ren dansroy2.mid anon_la_quarte_estampie_royal2.mid 
ren ductia.mid anon_la_uitime_estampie_real2.mid 
ren estamp01.mid anon_la_quinte_estampie_real2.mid 
ren estamp02.mid anon_la_seconde_estampie_royal2.mid 
ren estamp03.mid anon_estampie_x.mid 
ren grenslvs.mid anon_greensleeves.mid
ren staines.mid anon_staines_morris.mid
ren tflorwnd.mid anon_tempus_adest_floridum_winds.mid
ren arbbrlof.mid arbeau_branle_l_official.mid
ren arbjouys.mid arbeau_jouyssance_vous_donnerai.mid
ren froggall.mid anon_frog_galliard.mid
ren reihentz.mid anon_reihentaenze.mid
ren arbbchev.mid arbeau_bransle_des_chevaux.mid
ren arcocchm.mid arcadelt_occhi_miei_lassi.mid
ren dowcmagw.mid dowland_come_again_winds.mid
ren gervbuch.mid gervaise_burgundian-champagne.mid
ren gervmixb.mid gervaise_mixed_bransles_1_bransle_double.mid
ren moromist.mid morley_o_mistris_mine.mid
ren pracanar.mid praetorius_la_canarie.mid
ren susalle2.mid susato_allemande2.mid
ren susrondo.mid susato_rondo.mid
ren vecfaunc.mid vecchi_fa_una_canzone.mid
cls
