echo off
ren agricola_o_venus_bant.mid agrivenb.mid 
ren alison_quadro_pavin.mid quadro-p.mid 
ren anon_agnus_dei.mid agnusdei.mid 
ren anon_an_I_were_a_maiden.mid andiwere.mid 
ren anon_angelus_ad_virginem.mid anglvirg.mid 
ren anon_angelus_ad_virginem2.mid anglvirm.mid 
ren anon_as_I_was_walking.mid waswalkg.mid 
ren anon_be_peace_ye_make_me_spill_my_ale.mid bepeace.mid 
ren anon_bel_fiore_danca.mid belfiore.mid 
ren anon_benedicamus_domino.mid benedica.mid 
ren anon_cobblers_hornpipe.mid cobhrnpp.mid 
ren anon_conductus.mid conductu.mid 
ren anon_consort_xii.mid cons12.mid 
ren anon_country_jig.mid cntryjig.mid 
ren anon_czaldy_waldy.mid czaldy.mid 
ren anon_dadme_albricias_hijos_d'eva.mid dadme.mid 
ren anon_die_katzenpfote.mid katzpfot.mid 
ren anon_duo.mid duo17thc.mid 
ren anon_e_la_don_don_virges_maria.mid eladon.mid 
ren anon_edi_beo_thu_hevene_quene.mid edibeo.mid 
ren anon_elslein_liebstes_elslein.mid elslein.mid 
ren anon_gaudete.mid gaudete.mid 
ren anon_hey_ho_what_shall_I_say.mid whatshal.mid 
ren anon_ic_seg_adieu.mid ichsegad.mid 
ren anon_jeanette_isabella.mid jeanisab.mid 
ren anon_la_bergamasca.mid bergamas.mid 
ren anon_la_girometta.mid giromett.mid 
ren anon_la_rotta.mid la_rotta.mid 
ren anon_lamento_di_tristana.mid lamntris.mid 
ren anon_montagnura.mid montagnu.mid 
ren anon_nota_39.mid nota39.mid 
ren anon_nota_40.mid nota40.mid 
ren anon_nota_41.mid nota41.mid 
ren anon_now_thanked_be_the_great_god_pan.mid godpan.mid 
ren anon_omnis_curet_homo.mid omniscur.mid 
ren anon_pase_el_agua_ma_julieta.mid paseagua.mid 
ren anon_patapan.mid patapan.mid 
ren anon_pavane_for_shawm_band.mid pavnshwm.mid 
ren anon_piper's_fancy.mid pipfancy.mid 
ren anon_riu_riu_chiu.mid riuriu.mid 
ren anon_saltarello_2.mid saltare2.mid 
ren anon_saltarello_3.mid saltare3.mid 
ren anon_si_fortune.mid sifortun.mid 
ren anon_sing_care_away.mid singcare.mid 
ren anon_sumer_is_icumen_in_1.mid icumen.mid 
ren anon_sumer_is_icumen_in_2.mid icumen2.mid 
ren anon_tant_a_soutille.mid tantasou.mid 
ren anon_tempus_adest_floridum.mid tempflor.mid 
ren anon_the_agincourt_carol.mid agincour.mid 
ren anon_the_boar's_head_carol_1.mid boarhead.mid 
ren anon_the_boar's_head_carol_2.mid boarhed2.mid 
ren anon_the_coventry_carol.mid coventry.mid 
ren anon_the_holly_and_the_ivy.mid hollyivy.mid 
ren anon_the_shepherd's_hey.mid morris.mid 
ren anon_the_wassail_song.mid wassail.mid 
ren anon_there_is_no_rose_of_swich_vertu.mid no_rose.mid 
ren anon_this_day_day_daws.mid daydaws.mid 
ren anon_veni_veni_immanuel.mid veniveni.mid 
ren anon_verbum_caro_factum_est.mid verbcaro.mid 
ren arbeau_belle_qui_tiens_ma_vie.mid arbbelqu.mid 
ren attaignant_dance_suite.mid attdnsui.mid 
ren bassano_fanfare5.mid basnfan5.mid 
ren bassano_ricercar11.mid basnrc11.mid 
ren bennett_servant_of_his_mistress.mid bennserv.mid 
ren brade_der_ander_mascharada.mid bradanma.mid 
ren brade_der_erste_mascarada_des_pfaltzgraffen.mid braderma.mid 
ren busnois_fortuna_desperata.mid busnfods.mid 
ren byrd_hey_ho_to_the_greenwood.mid byrdgrnw.mid 
ren caccini_amor_ch'attendi.mid amorchat.mid 
ren cantigas_como_poden.mid comopodn.mid 
ren cantigas_santa_maria_amar.mid cdsmamar.mid 
ren cara_io_non_compro_piu_speranza.mid caranonc.mid 
ren clark_wherever_you_go.mid clkcwhrv.mid 
ren clark_wind_on_a_ground.mid clkcwngr.mid 
ren compere_alons_fere_nos_barbes.mid compbarb.mid 
ren cornysh_adieu_corage_adieu.mid cornadiu.mid 
ren cornysh_ah_robin_gentle_robin.mid cornrobn.mid 
ren cornysh_blow_thy_horne_hunter.mid cornblow.mid 
ren cornysh_trolly_lolly.mid corntrly.mid 
ren daggere_18_downbery_down.mid daggdown.mid 
ren daggere_18a_downbery_down.mid daggdowa.mid 
ren delahalle_jeu_de_robin_et_marion.mid jeurobin.mid 
ren delatorre_alta.mid torralta.mid 
ren desprez_vive_le_roy.mid despvive.mid 
ren dowland_a_shepherd_in_a_shade.mid dowshep.mid 
ren dowland_come_again_sweet_love_doth_now_invite.mid dowcmagn.mid 
ren dowland_if_my_complaints.mid dowcomp.mid 
ren encina_soy_contento_y_vos_servido.mid encisoyc.mid 
ren encina_triste_espana_sin_ventura.mid encitris.mid 
ren erars_au_tems_pascor.mid eraraute.mid 
ren escobar_lo_que_queda_es_lo_seguro.mid escolque.mid 
ren escobar_missa_de_nuestra_señora-pleni_sunt.mid escoplen.mid 
ren escobar_pasame_por_dios_varquero.mid escovarq.mid 
ren escobar_paseisme_aor'_alla_serrana.mid escoserr.mid 
ren escobar_vencedores_son_tus_ojos.mid escovenc.mid 
ren eustacio-romano_tenor_cum_tenore3.mid eusr3ten.mid 
ren eustacio-romano_tenor_cum_tenore7.mid eusr7ten.mid 
ren festa_l'ultimo_di_de_maggio.mid festumag.mid 
ren festa_o_passi_sparsi.mid festopas.mid 
ren gabrieli_canzone.mid gabacanz.mid 
ren gervaise_almande_1.mid gervalm1.mid 
ren gervaise_bransle_de_bourgongne_9.mid gervbbg9.mid 
ren gervaise_bransle_gay_1.mid gervbrg1.mid 
ren gervaise_bransle_gay_2.mid gervbrg2.mid 
ren gervaise_bransle_gay_3.mid gervbrg3.mid 
ren gervaise_bransle_gay_4.mid gervbrg4.mid 
ren gervaise_bransle_gay_5.mid gervbrg5.mid 
ren gervaise_bransle_gay_6.mid gervbrg6.mid 
ren gervaise_bransle_simple_1.mid gervbrs1.mid 
ren gervaise_gaillard_de_la_guerre.mid gervgaig.mid 
ren gervaise_gaillard_du_ton_de_la_guerre1.mid gervgtg1.mid 
ren gervaise_gaillard_du_ton_de_la_guerre2.mid gervgtg2.mid 
ren gervaise_gaillard_est_il_conclud.mid gervgaic.mid 
ren gervaise_gaillard_l'admiral.mid gervgaia.mid 
ren gervaise_gaillard_si_je_m'en_vois.mid gervgais.mid 
ren gervaise_pavanne_de_la_guerre.mid gervpavg.mid 
ren gervaise_pavanne_est_il_conclud.mid gervpavc.mid 
ren gervaise_pavanne_l'admiral.mid gervpava.mid 
ren gervaise_pavanne_si_je_m'en_vois.mid gervpavs.mid 
ren gesius_in_dulci_jubilo.mid jubilo.mid 
ren gibbons_the_silver_swanne.mid gibbswan.mid 
ren haynevanghizeghem_de_tous_bien_plane.mid ghizdetu.mid 
ren henryvi_sanctus.mid hen4sanc.mid 
ren henryviii_consort24.mid hen8cn24.mid 
ren henryviii_consort4.mid hen8con4.mid 
ren henryviii_en_vray_amoure.mid hen8envr.mid 
ren henryviii_gentil_prince.mid hen8gnpr.mid 
ren henryviii_helas_madame.mid hen8hmdm.mid 
ren henryviii_passetyme_with_good_cumpanye7.mid hen8pas2.mid 
ren henryviii_pastime_with_good_company7a.mid hen8past.mid 
ren henryviii_tander_nauken.mid hen8tndr.mid 
ren henryviii_whereto_shoulde_i_expresse.mid hen8whto.mid 
ren hilton_come_follow_follow_me.mid hiltcmfl.mid 
ren hilton_come_merry_men_follow.mid hiltcmmf.mid 
ren hilton_now_when_the_summer's_fruits.mid hiltsmfr.mid 
ren hilton_what_shall_he_have_that_kill'd_the_deer.mid hiltkldr.mid 
ren holborne_fruit_of_love.mid holbfrui.mid 
ren holborne_mvylinda.mid holbmvyl.mid 
ren holborne_the_choice.mid holbchoi.mid 
ren holborne_the_widow's_mite.mid holbwidm.mid 
ren isaac_gross_leid_muss_ich_tragen.mid isagleid.mid 
ren isaac_innsbruck_ich_muss_dich_lassen_r.mid isainnsr.mid 
ren isaac_innsbruck_ich_muss_dich_lassen_v.mid isainnsv.mid 
ren isaac_la_my.mid isa-lamy.mid 
ren landini_ballata.mid lndnbllt.mid 
ren landini_chi_piu_vuol_sapere.mid lndnchip.mid 
ren landini_partesi_con_dolore.mid lndnpart.mid 
ren landini_questa_fanciull'_amor.mid lndnques.mid 
ren lassus_oi_ch'el_mio_largo_pianto.mid lassoich.mid 
ren lassus_wohl_kommt_der_mai.mid las-mai.mid 
ren luther_vom_himmel_hoch.mid luthvhim.mid 
ren machaut_de_bonte_de_valour.mid machbont.mid 
ren machaut_dous_amis.mid machdous.mid 
ren manchicourt_que_puis_je_lors.mid mnchqupu.mid 
ren morley_blow_shepherds_blow_your_pipes.mid morlcan5.mid 
ren morley_farewell_disdainful.mid morlcan6.mid 
ren morley_good_morrow_fair_ladies_of_the_may.mid morlcan4.mid 
ren morley_lady_those_eyes.mid morlcan2.mid 
ren morley_o_sing_unto_the_lord_a_new_song.mid morlnews.mid 
ren morley_say_dear_will_you_not_have_me.mid morlcan9.mid 
ren morley_say_what_ails_my_darling.mid morlcan7.mid 
ren morley_see_mine_own_sweet_jewel.mid morlcan8.mid 
ren morley_springtime_mantleth_every_bough.mid morlcan1.mid 
ren morley_where_art_thou_wanton.mid morlcan3.mid 
ren moulu_amy_souffrez.mid moulamys.mid 
ren obreht_tandernaken.mid obrtandr.mid 
ren patavino_dilla_da_l'acqua.mid patadlla.mid 
ren perotin_alleluya.mid peroalle.mid 
ren perotin_alleluya_nativitas.mid peroalna.mid 
ren perotin_alleluya_nativitas_concert.mid 980429.mid 
ren pesenti_dal_lecto_me_levava.mid pesedlct.mid 
ren playford_rufty_tufty.mid rufty.mid 
ren praetorius_ballet_268.mid prabal10.mid 
ren praetorius_bouree_32a.mid prabou8.mid 
ren praetorius_bouree_32b.mid prabou9.mid 
ren praetorius_courante_117.mid pracour2.mid 
ren praetorius_courante_183.mid pracour1.mid 
ren praetorius_es_ist_ein_reis_entsprungen.mid einros.mid 
ren praetorius_gavotte_1.mid pragaval.mid 
ren praetorius_gavotte_1_abcf.mid pragavx.mid 
ren praetorius_gavotte_1_gillotte.mid pragil7.mid 
ren praetorius_gavotte_1a.mid pragav1.mid 
ren praetorius_gavotte_1b.mid pragav2.mid 
ren praetorius_gavotte_1c.mid pragav3.mid 
ren praetorius_gavotte_1d.mid pragav4.mid 
ren praetorius_gavotte_1e.mid pragav5.mid 
ren praetorius_gavotte_1f.mid pragav6.mid 
ren praetorius_spagnoletta_27.mid praspag7.mid 
ren praetorius_volte_202.mid pravol11.mid 
ren praetorius_volte_202_shawms.mid scrmshwm.mid 
ren praetorius_volte_210.mid pravol12.mid 
ren rampolini_bacco_bacco.mid rampbacc.mid 
ren ravenscroft_3ravens.mid 3ravens.mid 
ren richardi_ja_nuns_hons_pris.mid januns.mid 
ren senfl_ach_elslein_liebes_elselein_mein.mid senelse.mid 
ren senfl_als_ab_und_hin.mid senalsab.mid 
ren senfl_es_taget_vor_dem_walde.mid sentaget.mid 
ren senfl_es_taget_vor_dem_walde-fortuna.mid sentgfor.mid 
ren senfl_es_was_eins_bauren_toechterlein.mid senbaurt.mid 
ren senfl_es_wollt'_ein_maidlein_wasser_hol'n.mid seneswol.mid 
ren senfl_ich_stuend_an_einem_morgen.mid senistu3.mid 
ren senfl_lust_mag_mein_herz.mid senlumag.mid 
ren senfl_wann_ich_des_morgens_frueeh_aufsteh'_primum.mid senmrgf1.mid 
ren senfl_wann_ich_des_morgens_frueeh_aufsteh'_secundum.mid senmrgf2.mid 
ren senfl_wohl_kumbt_der_mai1.mid senwmai1.mid 
ren senfl_wohl_kumbt_der_mai2.mid senwmai2.mid 
ren sermisy_allez_souspirs.mid sermalle.mid 
ren sermisy_tant_que_vivrai.mid sermtviv.mid 
ren song_of_the_ass_1.mid song-ass.mid 
ren song_of_the_ass_2.mid songassf.mid 
ren susato_allemande.mid susallem.mid 
ren susato_hoboeckentanz.mid sushoboe.mid 
ren vecchi_so_ben_mi_cha_bon_tempo.mid vecsoben.mid 
ren white_hark_how_the_woods_do_ring.mid whimhrkh.mid 
ren willaert_le_dur_travail.mid wllaledu.mid 
ren delahalle_fi_maris_de_vostre_amour.mid hallfima.mid 
ren anon_verbum_caro_factum_est_in_hoc_anni_circulo.mid inhcanni.mid 
ren anon_i_am_a_jolly_foster.mid jollfost.mid 
ren anon_resonet_in_laudibus.mid resolaud.mid 
ren cantigas_de_santa_maria_1.mid cdsm1.mid 
ren anon_la_quarte_estampie_royal.mid estamp4.mid 
ren anon_jay_pryse_amours.mid jaypryse.mid 
ren anon_roundel_1453.mid roundel.mid 
ren viol_test.mid violtest.mid 
ren anon_viv_el_gran_re_don_fernando.mid vivrefrn.mid 
ren tye_while_shepherds_watched_their_flocks_by_night.mid whilshep.mid 
ren delete_ths_one.mid amysouff.mid 
ren anon_danse_(ductia_13)_2.mid dansroy1.mid 
ren anon_la_quarte_estampie_royal2.mid dansroy2.mid 
ren anon_la_uitime_estampie_real2.mid ductia.mid 
ren anon_la_quinte_estampie_real2.mid estamp01.mid 
ren anon_la_seconde_estampie_royal2.mid estamp02.mid 
ren anon_estampie_x.mid estamp03.mid 
ren anon_greensleeves.mid grenslvs.mid
ren anon_staines_morris.mid staines.mid
ren anon_tempus_adest_floridum_winds.mid tflorwnd.mid
ren arbeau_branle_l_official.mid arbbrlof.mid
ren arbeau_jouyssance_vous_donnerai.mid arbjouys.mid
ren anon_frog_galliard.mid froggall.mid
ren anon_reihentaenze.mid reihentz.mid
ren arbeau_bransle_des_chevaux.mid arbbchev.mid
ren arcadelt_occhi_miei_lassi.mid arcocchm.mid
ren dowland_come_again_winds.mid dowcmagw.mid
ren gervaise_burgundian-champagne.mid gervbuch.mid
ren gervaise_mixed_bransles_1_bransle_double.mid gervmixb.mid
ren morley_o_mistris_mine.mid moromist.mid
ren praetorius_la_canarie.mid pracanar.mid
ren susato_allemande2.mid susalle2.mid
ren susato_rondo.mid susrondo.mid
ren vecchi_fa_una_canzone.mid vecfaunc.mid
cls